const data = {
  products: [
    {
      name: "Draped Blouse",
      slug: "draped-blouse",
      category: "Shirts",
      image: "/images/draped-blouse-h&m.jpeg",
      price: 1500,
      brand: "H&M",
      rating: 4,
      numReviews: 30,
      countInStock: 50,
      description:
        "Short, fitted blouse with a square neckline and a small opening at the front with narrow straps that tie at the back of the neck. Gathered seams at the sides for a draped effect.",
    },
    {
      name: "Air Force 1",
      slug: "nike-air-force",
      category: "Shoes",
      image: "/images/nike-air-force-1.webp",
      price: 18000,
      brand: "Nike",
      rating: 4.9,
      numReviews: 100,
      countInStock: 50,
      description:
        "Bring yourself to the table with the original high-flyer. Fully customisable, it let's you be as expressive as you want. Choose between an original swoosh or a crystal inspired one.",
    },

    {
      name: "Jordan Flight MVP 85",
      slug: "statement-shirt",
      category: "Shirts",
      image: "/images/statement-shirt-nike.webp",
      price: 2700,
      brand: "Nike",
      rating: 4.5,
      numReviews: 75,
      countInStock: 30,
      description:
        "Bring the energy in a tee that reinterprets classic Jordan Brand imagery. Bold graphics make a statement on soft, relaxed cotton that you'll want to wear all day.",
    },
    {
      name: "Pintuck Pants",
      slug: "pintuck-pants",
      category: "Pants",
      image: "/images/pintuck-pants-adidas.webp",
      price: 4500,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 40,
      countInStock: 90,
      description:
        "The adidas Skateboarding Pintuck Pants provide the comfort of classic track pants with a loose fit for skateboarding, Inspired by an archival Beckenbauer pant.",
    },
    {
      name: "Loose Fit Sports T-Shirt",
      slug: "loose-fit-sports-t-shirt",
      category: "Shirts",
      image: "/images/loose-fit-t-shirt-puma.webp",
      price: 1300,
      brand: "Puma",
      rating: 4.2,
      numReviews: 40,
      countInStock: 60,
      description:
        "The Modern Sports Fashion T-Shirt from PUMA brings competitive flair to the street. With its elongated length, glossy PUMA Cat branding and bold colourblock design, this fresh T-Shirt is sure to turn heads. But it's never a case of style over substance with PUMA. This T-Shirt is made with our advanced dryCELL moisture-wicking technology for a comfortable, dry fit.",
    },
    {
      name: "Relaxed Fit Sweat Pants",
      slug: "relaxed-fit-sweat-pants",
      category: "Pants",
      image: "/images/relaxed-fit-sweat-pants-puma.webp",
      price: 4000,
      brand: "Puma",
      rating: 4.2,
      numReviews: 80,
      countInStock: 70,
      description:
        "A new season calls for another art collaboration - this time with Brazilian painter, sculptor and silk screen master Romero Britto. Famous for creating vibrant colours, bold patterns and dynamic details designed to convey hope and happiness, his work is unmistakable. Together, we create a '90s-inspired collection that brings an urban edge to street sophistication. Fiercely funky, with sleek lines, bold graphics and a relaxed, comfort-chic silhouette, these stylish Sweat Pants make casual look cool. Whether you're out on the town or lounging about, you'll look and feel your best.",
    },

    {
      name: "Lyocell Resort Shirt",
      slug: "lyocell-resort-shirt",
      category: "Shirts",
      image: "/images/lyocell-shirt-h&m.jpeg",
      price: 1500,
      brand: "H&M",
      rating: 4.2,
      numReviews: 150,
      countInStock: 200,
      description:
        "Short-sleeved shirt in softly draping, patterned lyocell with a resort collar, French front and yoke at the back. Flap chest pockets, and a straight-cut hem with slits in the sides.",
    },
    {
      name: "Questar HM Shoes",
      slug: "questar-hm-shoes",
      category: "Shoes",
      image: "/images/questar-hm-shoes-adidas.jpeg",
      price: 9000,
      brand: "Adidas",
      rating: 4.6,
      numReviews: 80,
      countInStock: 60,
      description:
        "A grand influence on culture, Human Made touches all corners in the world of art. In collaboration with adidas, the Japanese label lends their vision to these Questar shoes. Contrast colours pop from the leather upper, all playing together to make a bold impression.",
    },
    {
      name: "Porsche Legacy Pants",
      slug: "porsche-legacy-pants",
      category: "Pants",
      image: "/images/porsche-legacy-statement-pants-puma.webp",
      price: 7000,
      brand: "Puma",
      rating: 4.6,
      numReviews: 90,
      countInStock: 50,
      description:
        "The Statement collection is deeply rooted in the strong legacy of Porsche Legacy motorsport. This season, we took the 911 Rallye as our inspiration. Through design details and powerful graphics, we celebrate joy, history, passion, and the colours seen trackside. Pop them on and you'll be looking just as good as your favourite Porsche Legacy race car drivers when you take the 911 for a spin.",
    },
    {
      name: "TRC Blaze SWxP Sneakers",
      slug: "trc-blaze-sneakers",
      category: "Shoes",
      image: "/images/trc-blaze-sneakers-puma.webp",
      price: 10000,
      brand: "Puma",
      rating: 4.8,
      numReviews: 110,
      countInStock: 70,
      description:
        "TRC Blaze, a futuristic take on the classic Trinomic, celebrates the notion that when individuals or elements come together and connect, magic happens. These bold and bright sneakers are a nod to our loud and proud sportswear heritage. Vibrant and playful, they bring fresh vibes thanks to a combination of suede and mesh textures on the upper, plus an A-frame overlay with embossed details and a graphic printed line.",
    },

    {
      name: "Reversible Track Pants",
      slug: "reversible-track-pants",
      category: "Pants",
      image: "/images/reversible-track-pants-hm.jpeg",
      price: 4000,
      brand: "H&M",
      rating: 4.7,
      numReviews: 130,
      countInStock: 80,
      description:
        "Relaxed-fit track pants in fast-drying functional fabric with good air permeability to wick away moisture and help keep you dry and cool while exercising. The pants are reversible with one side in woven fabric with a reflective monogram pattern and the other side in solid colour mesh with reflective side panels.",
    },
    {
      name: "Polo Shirt",
      slug: "polo-shirt",
      category: "Shirts",
      image: "/images/nike-polo-shirt.webp",
      price: 3300,
      brand: "Nike",
      rating: 3.9,
      numReviews: 46,
      countInStock: 30,
      description:
        "This isn't your average polo—it's The Nike Polo. Every detail, from its innovative, sweat-wicking fabric to the hints of orange that nod to Nike's original shoe box, has been thoughtfully crafted to meet the needs of the everyday you.",
    },

    {
      name: "Tech Fleece Trousers",
      slug: "tech-fleece-trousers",
      category: "Pants",
      image: "/images/tech-fleece-trousers-nike.webp",
      price: 5700,
      brand: "Nike",
      rating: 4.2,
      numReviews: 50,
      countInStock: 40,
      description:
        "Explore the Nike Sportswear Swoosh Tech Fleece Men's Trousers. Smooth on both sides, Tech Fleece delivers impressive warmth and an elevated look without adding weight or bulk.",
    },
    {
      name: "Hi-top Trainers",
      slug: "hi-top-tainers",
      category: "Shoes",
      image: "/images/hi-top-trainers-h&m.jpeg",
      price: 3000,
      brand: "H&M",
      rating: 4.2,
      numReviews: 60,
      countInStock: 20,
      description:
        "Hi-top trainers with a padded top edge, a loop at the back, and lacing and a tongue with a loop at the front. Piqué linings, canvas insoles and patterned soles. These trainers will let you stay comfortable while being fashionable.",
    },
    {
      name: "Red Bull Racing Printed T-Shirt",
      slug: "redbull-racing-printed-t-shirt",
      category: "Shirts",
      image: "/images/red-bull-racing-printed-t-shirt-puma.webp",
      price: 3500,
      brand: "Puma",
      rating: 4.3,
      numReviews: 70,
      countInStock: 30,
      description:
        "We've joined forces with the famed F1 team to create a range of impactful leisurewear for all those adrenaline junkies out there who love the thrill of the race. So rev up your wardrobe with this eye-popping all-over-printed tee from our official Red Bull Racing collaboration – capturing the suavity and class of the legendary racers.",
    },
    {
      name: "Firebird Primeblue Track Pants",
      slug: "firebird-primeblue-track-pants",
      category: "Pants",
      image: "/images/firebird-primeblue-track-pants-adidas.webp",
      price: 3000,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 90,
      countInStock: 50,
      description:
        "The heart of adidas Originals, Adicolor is for the purist and the pioneer. This update of the Firebird pants keeps the look true to its roots, but spins it with recycled materials. Put your own stamp on an icon, and on the future. This product is made with Primeblue, a high-performance recycled material made in part with Parley Ocean Plastic.",
    },
    {
      name: "Air Max Flyknit Racer",
      slug: "air-max-flyknit-racer",
      category: "Shoes",
      image: "/images/nike-airmax-flyknit-racer.jpeg",
      price: 15000,
      brand: "Nike",
      rating: 4.8,
      numReviews: 115,
      countInStock: 80,
      description:
        "Paying homage to both heritage and innovation, we've blended 2 icons (old and new) to go beyond what's expected in the Nike Air Max Flyknit Racer. Incredibly light and airy Flyknit is paired with oh-so-comfy Air Max cushioning. Lace up and let your feet do the talking.",
    },
    {
      name: "Printed T-shirt",
      slug: "printed-t-shirt",
      category: "Shirts",
      image: "/images/printed-t-shirt-h&m.jpeg",
      price: 1300,
      brand: "H&M",
      rating: 4,
      numReviews: 120,
      countInStock: 70,
      description:
        "Smiley x H&M. T-shirt in soft, printed cotton jersey. Relaxed fit with a round, rib-trimmed neckline and dropped shoulders. This fun printed t-shirt will definitely win you over.",
    },
    {
      name: "Future Rider Play On Sneakers",
      slug: "future-rider-play-on-sneakers",
      category: "Shoes",
      image: "/images/future-rider-play-on-sneakers-puma.jpeg",
      price: 8000,
      brand: "Puma",
      rating: 4.3,
      numReviews: 127,
      countInStock: 70,
      description:
        "Keep the game going in the shoe that launched a movement, our Future Rider Play On Sneakers. This shoe is dedicated to pared-down performance, featuring a super-light nylon, suede and leather upper and our famous shock-absorbing Federbein outsole to keep you pounding the pavement in style.",
    },
    {
      name: "Rich Mnisi Tee",
      slug: "rich-mnisi-tee",
      category: "Shirts",
      image: "/images/rich-mnisi-tee-adidas.webp",
      price: 2000,
      brand: "Adidas",
      rating: 4,
      numReviews: 90,
      countInStock: 40,
      description:
        "South African designer Rich Mnisi has carved out his place in the world of fashion by unearthing Africa's hidden treasures and celebrating his heritage. This adidas t-shirt keeps that same intent alive. The pop art rose design honours the valour of a suitor scouring a garden to pick the perfect rose that can match the beauty of his beloved. Cotton single jersey is soft and breathable to keep you comfortable all day long.",
    },
  ],
};

export default data;
